# Generated by Django 4.0.4 on 2022-06-14 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertVoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('is_voted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product1mark', models.IntegerField()),
                ('product2mark', models.IntegerField()),
                ('product3mark', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Ассортимент', 'verbose_name_plural': 'Ассортименты'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Ассортимент'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='furniture.category', verbose_name='Принадлежность к ассортименту'),
        ),
    ]
