# Generated by Django 4.0.4 on 2022-06-15 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_expertvoted_productvote_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admincreatevote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category1', to='furniture.category', verbose_name='Принадлежность к ассортименту')),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category2', to='furniture.category', verbose_name='Принадлежность к ассортименту')),
                ('category3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category3', to='furniture.category', verbose_name='Принадлежность к ассортименту')),
            ],
        ),
    ]
